version: 2
jobs:
  deployment:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy Master to Heroku
            command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  build:
    docker:
      - image: circleci/node:6-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v4-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v4-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v4-dependencies-{{ checksum "package.json" }}
      - run:
          name: Installing PM2
          command: sudo npm install pm2 -g
      - run: npm run test
      - run: npm run prod
      - run: npm run serve
      - run: npm run featuretest
      - run: sudo npm install sonar-scanner -g
      - run: sonar-scanner
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deployment
